version: '3.2'

services: 
  td-report-engine:
    image: td-report-engine
    build:
        context: .
        dockerfile: development.dockerfile
    volumes:
        - "../.:/td-report-engine"
        - "../files/etc/td-report-engine:/etc/td-report-engine"
    ports:
        - "4321:4321"
    depends_on:
        - elasticsearch
    command: ["refresh","run","-c",".dev/refresh.yaml"]
    container_name: td-report-engine
  elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.5.1
        environment:
          - discovery.type=single-node
          - http.cors.allow-origin="*"
          - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
          - xpack.security.enabled=false
          - http.cors.allow-credentials=true
          - cluster.name=es-docker-cluster          - bootstrap.memory_lock=true
          - http.cors.enabled=true
          - "ES_JAVA_OPTS=-Xms728m -Xmx728m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ../.dev/elasticdata:/usr/share/elasticsearch/data:rw
        ports:
            - 9200:9200
  kibana:
      image: kibana:7.5.1
      container_name: kibana
      ports:
          - "5601:5601"
      links:
          - elasticsearch
  cerebro:
      image: lmenezes/cerebro:0.8.3
      container_name: cerebro
      ports:
        - "9100:9000"